% Tesis ITAM CLASS -- version 0.1 (13 - Abr - 2015)
% Clase para las tesis del ITAM
% 
% 13 - Abr - 2015 	Victor Martinez 	victor.martinez (at) itam.mx
% 13 - Abr - 2015 	Jesus Arroyo 		
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{tesisITAM}[2015/04/13 v0.01 Template para tesis ITAM]

% Options


% Usamos como clase base el de report
\LoadClass[a4paper, oneside]{report}


% Paquetes requeridos
\RequirePackage{babel}

